/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.vagtsi.examples.guicejavamodule.parent;

import org.junit.jupiter.api.Test;
import com.google.inject.Binder;
import com.google.inject.Module;

import de.vagtsi.examples.guicejavamodule.greeting.core.GreetingCorePlugin;

import static org.junit.jupiter.api.Assertions.*;

class ParentPluginTest {
    @Test
    void pluginTestImplementation() {
      GreetingCorePlugin testPlugin = new GreetingCorePlugin() {
        @Override
        public String id() {
          return "test-plugin";
        }
        
        @Override
        public Module module() {
          return new Module() {
            @Override
            public void configure(Binder binder) {
            }
          };
        }
      };
      
      assertNotNull(testPlugin.id(), "Plugin id is mandatory");
      assertNotNull(testPlugin.module(), "Plugin guice module is mandatory");
    }
}
