/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.vagtsi.examples.guicejavamodule.greeting.french;

import com.google.inject.Module;
import de.vagtsi.examples.guicejavamodule.api.PluginModule;

public class FrenchGreetingPlugin implements PluginModule {
  
  @Override
  public String id() {
    return "french-greeting-plugin";
  }
  
  @Override
  public Module module() {
    return new FrenchGreetingModule();
  }
  
  @Override
  public String[] parentIds() {
    return new String[] { "greeting-core" };
  }
}
