/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.vagtsi.examples.guicejavamodule.greeting.core;

import com.google.inject.Module;
import de.vagtsi.examples.guicejavamodule.api.PluginModule;

public class GreetingCorePlugin implements PluginModule {
  
  @Override
  public String id() {
    return "greeting-core";
  }
  
  @Override
  public Module module() {
    return new GreetingCoreModule();
  }
}
